# .github/workflows/deploy-terraform.yml
name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main          # jab main branch pe push ho
      - feature/*     # jab feature branches pe push ho

jobs:
  terraform-init-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Terraform Init
        run: terraform init
        working-directory: environment/dev
        with:
          azure_credentials: {{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: sumit
          container_name: sumit123456
          storage_account_name: sumit123456
          file_name: dev.tfstate

      - name: Terraform Validate
        run: terraform validate
        working-directory: environment/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: environment/dev

  terraform-apply:      
    runs-on: ubuntu-latest
    needs: terraform-init-plan
    environment: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Terraform Init
        run: terraform init
        working-directory: environment/dev


      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: environment/dev
